global:
  scrape_interval: 5s

rule_files:
  - "alert.rules.yml"

scrape_configs:
  - job_name: 'spring-boot-full'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['app:8080']
