{
 "title": "Spring Boot Observability Dashboard",
 "tags": [
  "spring-boot",
  "prometheus",
  "demo"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Requests per Second (TPS)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count[1m]))",
     "legendFormat": "TPS"
    }
   ]
  },
  {
   "title": "Error Rate (5xx %)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * (sum(rate(http_server_requests_seconds_count{status=~\"5..\"}[2m])) / sum(rate(http_server_requests_seconds_count[2m])))",
     "legendFormat": "Error %"
    }
   ]
  },
  {
   "title": "Response Time P95 (ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_server_requests_seconds_bucket[5m])) by (le)) * 1000",
     "legendFormat": "P95 latency"
    }
   ]
  }
 ]
}